spring.application.name=gitoo
spring.datasource.url=jdbc:mysql://localhost:3306/gitoo?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password =MySQL0208andy^^
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret-key=vmfhaltmasktptwhskshqdmstnwhrgkrptjtrmatpdnjshm32vmfhaltmasktptwhskshqdmstnwhrgkrptjtrmatpdnjshm32
security.jwt.expiration-time=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ask0208ask@gmail.com
spring.mail.password = wsgefamdhydrgyap
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.cors=DEBUG
