spring.application.name=gitoo
spring.datasource.url=jdbc:mysql://localhost:3306/gitoo?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password =csedbadmin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret-key=vmfhaltmasktptwhskshqdmstnwhrgkrptjtrmatpdnjshm32vmfhaltmasktptwhskshqdmstnwhrgkrptjtrmatpdnjshm32
security.jwt.expiration-time=3600000

neis.base-url=https://open.neis.go.kr/hub
neis.key=42809c6b2ec34d19930c579f4e3509d1
neis.type=json
neis.pIndex=1
neis.pSize=50

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kgykdy@gmail.com
spring.mail.password = rsqebooxozjsdsyc
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.cors=DEBUG
